--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Ifera/ScoreHudX
build-by-default: true
branches:
- main
projects:
  BasicScore:
    path: BasicScore
  EcoAPIScore:
    path: EcoAPIScore
...
