--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Ifera/ScoreHudX
build-by-default: true
branches:
- main
projects:
  BasicScore:
    path: BasicScore
    lint:
      phpstan: false
  EcoAPIScore:
    path: EcoAPIScore
    lint:
      phpstan: false
  CombatScore:
    path: CombatScore
    lint:
      phpstan: false
  FactionsProScore:
    path: FactionsProScore
    lint:
      phpstan: false
  PurePermsScore:
    path: PurePermsScore
    lint:
      phpstan: false
...
